### ISSUE TITLE
[NEW] Emby PiP播放

### ISSUE THREAD

**Issue by qinyuhang** [alexiscn/FileboxFeedback#15]
### 需求功能

Emby 播放无法PiP，希望可以增加PiP播放。

**Comment by alexiscn** [comment]
由于系统限制，只有部分格式的视频支持小窗播放，比如 mp4、mov。理论上所有的本地视频都支持小窗播放，网络上的视频随缘支持小窗播放。

其他播放器如果支持非mp4的小窗，是因为他们重新渲染了一遍，交给系统播放器去放（进行下载、解码、传输等）。 Filebox 是将播放器地址丢给系统播放器，如果系统播放器告诉我可以小窗，那么就有小窗。
