### ISSUE TITLE
[Bug] 长按倍速播放之后，细微滑动就会触发滑动快进/快退

### ISSUE THREAD

**Issue by qinyuhang** [alexiscn/FileboxFeedback#19]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

v1.1.17(3)

### 遇到的错误

在使用长按倍速播放的功能的时候，如果不小心再轻微左右滑动一下（可能就是几像素）会直接快进或者快退，其实在按住的时候很难就保证固定在一个地方。
可否做长按播放的时候添加一个容错范围（比如50pt之内不能滑动不触发快进快退）

**Comment by alexiscn** [comment]
fixed in 1.1.18 build 4
