### ISSUE TITLE
[NEW] ipad播放时隐藏上方的日期时间等信息

### ISSUE THREAD

**Issue by SOREMUZ** [alexiscn/FileboxFeedback#20]
### 需求功能

希望ipad播放时可以隐藏上方的时间

### 如果您能够简略提供使用场景就更好了！

![2021-12-01 17 11 10](https://user-images.githubusercontent.com/64671591/144205508-8d88b3dc-7d82-4453-a874-2e08415b058f.jpg)
如图 希望可以去掉

**Comment by alexiscn** [comment]
Fixed in TestFlight 1.1.17 build 23
