### ISSUE TITLE
[NEW] 播放视频时显示网速/缓存信息

### ISSUE THREAD

**Issue by qinyuhang** [alexiscn/FileboxFeedback#21]
### 需求功能

希望在播放视频的时候可以展示网速/缓存信息，方便判断现在的网络情况排查一些使用问题。这个功能，影音包里面有实现。

**Comment by alexiscn** [comment]
1.1.17 build 20

新增了网速信息，需要在设置中开启。

如果已经修正，烦请关闭该Issue，谢谢。

**Comment by qinyuhang** [comment]
其实这个是希望是实时网速。可能是表述的有点问题。。
![photo_2021-12-03_21-47-07](https://user-images.githubusercontent.com/6239057/144612924-7729c14f-bc76-4b7e-ad27-59f982628384.jpg)

**Comment by alexiscn** [comment]
网速信息已增加，缓冲信息暂时不准备加。
added in 1.1.18 build 5
