### ISSUE TITLE
[Bug] 阿里云盘视频无法播放

### ISSUE THREAD

**Issue by Sliccic** [alexiscn/FileboxFeedback#25]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

V1.1.16(82)

### 遇到的错误

阿里云界面加载很快，点进视频播放界面也较快，总时长也可以显示，但就是一直转圈黑屏加载不出来

**Comment by alexiscn** [comment]
should be fixed. Reopen if issue exists.
