### ISSUE TITLE
[NEW] 进入阿里云盘/谷歌盘，标题显示改为备注或者标题，而不是 AliyunDrive/GoogleDrive

### ISSUE THREAD

**Issue by qinyuhang** [alexiscn/FileboxFeedback#27]
### 需求功能

如图，点击进入阿里云盘/谷歌盘，显示的标题是 AliyunDrive/GoogleDrive，希望显示为添加的备注/标题。这样在有多个的时候能知道用的是哪个。
![IMG_6583](https://user-images.githubusercontent.com/6239057/144355358-f49ea2a2-2631-4691-b666-420d8dc1ca81.PNG)
![IMG_6584](https://user-images.githubusercontent.com/6239057/144355366-07a491d4-5a78-45f7-a9fa-e9ed41d206fb.PNG)
![IMG_6585](https://user-images.githubusercontent.com/6239057/144355373-184e7756-293c-4d1b-b446-7c19019f65d8.PNG)

**Comment by alexiscn** [comment]
Fixed in 1.1.17 build 5
