### ISSUE TITLE
[Bug] 阿里云盘批量重命名预览效果不会变

### ISSUE THREAD

**Issue by CHEN1016** [alexiscn/FileboxFeedback#34]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

1.1.17(5)

### 遇到的错误

阿里云盘批量重命名，修改在名字之前或者在名字之后，预览效果不会变

**Comment by Kosette** [comment]
不光是预览不会改变，而且修改只对部分项目生效，有bug。版本1.1.17(20)。

**Comment by CHEN1016** [comment]
> 不光是预览不会改变，而且修改只对部分项目生效，有bug。版本1.1.17(20)。

是的

**Comment by Kosette** [comment]
> 不光是预览不会改变，而且修改只对部分项目生效，有bug。版本1.1.17(20)。

经测试，一次最多只能批量命名10个文件。

**Comment by alexiscn** [comment]
fixed in 1.1.18 build 2
