### ISSUE TITLE
[NEW] 收藏那里能不能铺满屏而不是现在这样就横向一排

### ISSUE THREAD

**Issue by ssin0** [alexiscn/FileboxFeedback#36]
### 需求功能

下面好大的空
![8340D77C-083C-4F82-9D85-2A8AB1FAC632](https://user-images.githubusercontent.com/59248214/144555123-af9f91b2-9170-4b38-bf21-e306fc841c19.jpeg)

**Comment by alexiscn** [comment]
为什么这么设计？

因为收藏的不仅仅是节目，还有电影、音乐专辑、演员等等。 所以参考了 emby 的设计做成类似首页的样式，暂时不处理了。
