### ISSUE TITLE
[Bug] 重命名对话框 - 只能显示对应文件夹图标但不能够显示文件图标/缩略图

### ISSUE THREAD

**Issue by BingoKingo** [alexiscn/FileboxFeedback#37]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

1.16

### 遇到的错误

重命名文件

**Comment by alexiscn** [comment]
Fixed in 1.1.17 build 20

Please verify it. Reopen this issue if issue still exists.
