### ISSUE TITLE
[NEW] 添加拖拽手势

### ISSUE THREAD

**Issue by congnews** [alexiscn/FileboxFeedback#39]
### 需求功能

在媒体服务等需要整理资源的情况中、新建文件夹、选中文件便可拖拽到文件夹里、可以大大提高整理资料的效率！

### 如果您能够简略提供使用场景就更好了！

例如云盘中下载的资源并没有按照季进行分类、而是混在一起、那可以新建文件夹、选中一个季里面的文件拖拽到文件夹中、完成分类！

**Comment by alexiscn** [comment]
implemented
