### ISSUE TITLE
[Bug] 视频播放器修改字体会重置

### ISSUE THREAD

**Issue by realx1n** [alexiscn/FileboxFeedback#44]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

1.1.17（21）

### 遇到的错误

视频播放器修改字体没生效，会重置成默认字体

**Comment by alexiscn** [comment]
Fixed in 1.1.17 build 22.

Please check it and close this issue if fixed.
