### ISSUE TITLE
[Bug] 视频播放器和文本编辑器选择字体界面不一致，且有UI问题

### ISSUE THREAD

**Issue by realx1n** [alexiscn/FileboxFeedback#45]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

1.1.17(21)

### 遇到的错误

字体选择界面不一致，文本编辑器选择字体页面UI有问题
![172AE52B-EA9F-411A-A84D-4393874ACD67](https://user-images.githubusercontent.com/25891244/144701411-686f5b61-9dc7-41e8-a9a2-ca8507e7af5e.png)
![E0759D77-0A23-4E76-9919-ADE09C366A78](https://user-images.githubusercontent.com/25891244/144701412-0c441b77-58f4-4e77-9662-0732775c5e4b.png)

**Comment by alexiscn** [comment]
fixed in 1.1.18 build 2
