### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sorrymyself** [alexiscn/FileboxFeedback#46]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

tf v1.7.71（23） iOS15.0.2正式版 iPhone12

### 遇到的错误

连续剧不能点击下一曲，左上角的x号触摸不灵敏，在画中画模式播放的同时播放另一个剧集会出现两种不同的音频

**Comment by alexiscn** [comment]
fixed in 1.1.18 build 3
