### ISSUE TITLE
[Bug]  没有重头播放选项 继续播放播不出来

### ISSUE THREAD

**Issue by charliecui** [alexiscn/FileboxFeedback#50]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

v1.1.16 (82)

### 遇到的错误

视频从头都可以播放 推出继续播放就不好用 但是没有从头播放选项

**Comment by alexiscn** [comment]
implement in 1.1.40. Please hold play button to use start from beginning. 

Note: only Emby supported.
