### ISSUE TITLE
[Bug] 阿里云盘加载外挂字幕不显示

### ISSUE THREAD

**Issue by Kosette** [alexiscn/FileboxFeedback#52]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

1.1.17（86）

### 遇到的错误

手动选择加载外部字幕文件后，首次可以生效显示，重新播放后，再次选择相同字幕文件提示`temp`文件已经存在，且不显示字幕

### 补充说明（可选）

OSVerion: 15.1

**Comment by alexiscn** [comment]
fixed in 1.1.39
