### ISSUE TITLE
[Bug] 选择字幕大小以后字幕没变化

### ISSUE THREAD

**Issue by Ansned** [alexiscn/FileboxFeedback#58]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

Tf1.1.18(3)

### 遇到的错误

切换字幕大小，字幕不发生变化

### 补充说明（可选）

![Uploading 7B677ABF-E717-4283-9921-304FF8D0D905.png…]()

**Comment by alexiscn** [comment]
字幕大小仅对外挂字幕生效，内嵌字幕不起作用。

请问这是外挂字幕吗

**Comment by Ansned** [comment]
Odyssey ，彗星来的那一夜，default
PGSSUB字幕，另外，终点站，了不起的麦瑟尔夫人第一季，播放时选择字幕会所有的字幕都消失，只能退出重新重进，但是重进之后还是无法选择字幕


alexiscn ***@***.***>于2021年12月12日 周日下午10:41写道：

**Comment by alexiscn** [comment]
fixed
