### ISSUE TITLE
[Bug] 页面显示正在缓冲，但是声音已经在播放了

### ISSUE THREAD

**Issue by Ansned** [alexiscn/FileboxFeedback#59]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

Tf1.1.18(3)

### 遇到的错误

网速较慢的时候，页面显示正在缓冲，但是声音已经在正常播放了

**Comment by alexiscn** [comment]
Duplicate of #8
