### ISSUE TITLE
[NEW] 增加挂载Files App中文件夹的功能

### ISSUE THREAD

**Issue by Kosette** [alexiscn/FileboxFeedback#6]
### 需求功能

1. 增加挂载外部文件夹功能
2. (optional)增加open in place功能

### 如果您能够简略提供使用场景就更好了！

挂载外部文件夹可以实现在一处管理、查看多处（跨app）的文件，大大扩展app的使用场景，open in place则是为了在某些情况下利用app的内置的文本编辑功能编辑处理外部文件，从而免去到处拷贝导出文件的烦恼，简化流程

**Comment by alexiscn** [comment]
implemented in 1.1.38.
