### ISSUE TITLE
[NEW] 原则字幕时可以保持字幕在播放条上方，不被遮挡

### ISSUE THREAD

**Issue by Ansned** [alexiscn/FileboxFeedback#60]
### 需求功能

播放过程中原则字幕的时候，播放条会把字幕挡住，看不见，能不能在选择字幕的时候，让字幕自动显示在播放条上方，这样字幕就能被看到了

**Comment by alexiscn** [comment]
现在可以移动字幕位置，但是只支持mpv播放器
