### ISSUE TITLE
[Bug] 取消全选的状态会保留到手动取消为止

### ISSUE THREAD

**Issue by Kosette** [alexiscn/FileboxFeedback#61]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

1.1.18(3)

### 遇到的错误

全选之后，不管进行什么操作，再次选择时都保留着“取消全选”的状态，需要手动取消。
如图，
![IMG_1278797](https://user-images.githubusercontent.com/35268640/145567604-722f5f3c-fbea-449f-b9ac-aa14d2118892.jpg)

**Comment by alexiscn** [comment]
fixed in 1.1.18 build 5
