### ISSUE TITLE
[Bug] 播放器上显示的小标题和iPad的分屏按钮重合了

### ISSUE THREAD

**Issue by velazquez111** [alexiscn/FileboxFeedback#62]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

V1.1.18(4)

### 遇到的错误

![4B9F61B4-AE00-42E7-A3C8-F43F4A579102](https://user-images.githubusercontent.com/40903820/145681704-ed17a02c-a464-4c2a-ad0d-853fbbb0e5a2.jpeg)

如图上面中间的标题与分屏的三点按钮重合
用的是iPad 12.9寸

**Comment by alexiscn** [comment]
fixed in 1.1.18 build 5
