### ISSUE TITLE
[NEW] 增加一个iCloud文件夹

### ISSUE THREAD

**Issue by KadokawaJP** [alexiscn/FileboxFeedback#64]
### 需求功能

增加iCloud文件夹路径，通过iCloud同步在不同设备上使用Filebox读取云端文件。

### 如果您能够简略提供使用场景就更好了！

用iCloud听歌，节省存储空间，还可以在设备间同步文件，无需传到每个设备。

**Comment by IceJust** [comment]
> ### 需求功能
> 增加iCloud文件夹路径，通过iCloud同步在不同设备上使用Filebox读取云端文件。
> 
> ### 如果您能够简略提供使用场景就更好了！
> 用iCloud听歌，节省存储空间，还可以在设备间同步文件，无需传到每个设备。
