### ISSUE TITLE
[Bug] 无法正常显示PGS格式字幕

### ISSUE THREAD

**Issue by SOREMUZ** [alexiscn/FileboxFeedback#70]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

V.1.18(7)

### 遇到的错误

pgs格式的字幕变形

来源：终点站No.2的 《新哥斯拉》FHD版本的中文字幕 Default PGSSUB

![IMG_3547](https://user-images.githubusercontent.com/64671591/145951647-77495dcf-2bde-4d71-99ff-779ebe075efe.PNG)
![IMG_3546](https://user-images.githubusercontent.com/64671591/145951653-9c2a0465-4928-4e50-b034-7966576c1fcb.PNG)

**Comment by alexiscn** [comment]
Please try with MPV player
