### ISSUE TITLE
[NEW] 希望缓冲过程中可以长亮，不灭屏

### ISSUE THREAD

**Issue by Ansned** [alexiscn/FileboxFeedback#72]
### 需求功能

目前filebox里还有一切播放的bug，比如一直缓冲不播放，也有可能是网络问题缓冲比较慢，在这过程过因为是缓冲不是播放就会灭屏，希望可以增加缓冲的时候也可以和播放一样，不灭屏

**Comment by alexiscn** [comment]
MPV 播放器已经修正了该bug，VLC 不打算修此问题了
