### ISSUE TITLE
[Bug] 从媒体库处，点击播放后，没有下一集按钮，也不会接着播放下一集

### ISSUE THREAD

**Issue by zzzddd897** [alexiscn/FileboxFeedback#78]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

tf 1.1.19(9)

### 遇到的错误

如题

**Comment by alexiscn** [comment]
会在下个tf 版本中修正，感谢反馈

**Comment by alexiscn** [comment]
fixed in 1.1.19 build 14
