### ISSUE TITLE
[Bug] 超过12集剧集在继续播放中只显示前十二集

### ISSUE THREAD

**Issue by QiongBan** [alexiscn/FileboxFeedback#79]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

V1.1.18(88)

### 遇到的错误

Emby观看剧集数超过12的剧集，如犯罪现场调查（问题在终点站中出现，其他公益服未尝试）

**Comment by alexiscn** [comment]
fixed in 1.1.19 build 12
