### ISSUE TITLE
[Bug] mpv播放器  无法选择字幕，播放前选择字幕不生效

### ISSUE THREAD

**Issue by Ansned** [alexiscn/FileboxFeedback#83]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

1.1.20  6

### 遇到的错误

1.奥德赛服和终点站都会有这个问题，测试案例青春猪头少年不做兔女郎学姐的梦

2.还有个小小的建议，mpv手势调节屏幕亮度时不如vlc顺滑，当然只是小问题可修可不修

**Comment by alexiscn** [comment]
fixed in 1.1.20 build 10
