### ISSUE TITLE
[Bug] ipad侧边栏「我的收藏」文案有误

### ISSUE THREAD

**Issue by buhuizhuce** [alexiscn/FileboxFeedback#85]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

V1.1.26（5）

### 遇到的错误

ipad侧边栏「我的收藏」下边内容为并非收藏的内容，而是「连接」，目前文案有误。

**Comment by alexiscn** [comment]
fixed in 1.1.31
