### ISSUE TITLE
[NEW] 希望可以显示iptv里面的分组

### ISSUE THREAD

**Issue by JessYi228** [alexiscn/FileboxFeedback#87]
### 需求功能

希望可以显示这样的iptv的分组  
![8A8DEEB2-AAC0-420F-9864-716738815909](https://user-images.githubusercontent.com/64794054/155844930-d64e2e27-4737-4c2c-85f4-1a7eff749e5c.jpeg)

**Comment by alexiscn** [comment]
implemented
