### ISSUE TITLE
[Bug] mpv播放4k时选择裁剪满屏显示比例会缩小

### ISSUE THREAD

**Issue by lyk0803** [alexiscn/FileboxFeedback#89]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

1.1.28

### 遇到的错误

mpv播放4k时选择裁剪满屏显示比例会缩小，播放1080p的视频选择满屏字幕会遮挡
![7E22BC9F-2A80-49DC-B0E9-2198E9EAF12F](https://user-images.githubusercontent.com/67721358/156915002-5fa87760-8bf3-471b-a00e-f37644246632.png)
![BEF52FA5-8279-4939-9EEE-B89B9A5B0C7D](https://user-images.githubusercontent.com/67721358/156915003-ba9db68b-106f-47ad-8f6a-1941a7ff8906.png)
![37CD6D68-AC6D-487E-95F7-91688F4C89DC](https://user-images.githubusercontent.com/67721358/156915005-907293ff-a0a7-4bb7-a07f-c8755efc2c43.png)

**Comment by alexiscn** [comment]
fixed in 1.1.40

**Comment by alexiscn** [comment]
Please try it with MPV player.
