### ISSUE TITLE
[Bug] 列表和图标模式下显示的一系列问题

### ISSUE THREAD

**Issue by Kosette** [alexiscn/FileboxFeedback#9]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [X] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

1.1.16(82) AppStore

### 遇到的错误

1. 图标模式下显示出现重叠，主要是文件时间显示过长，测试与设备屏幕尺寸无关
![IMG_1260.jpg](https://i.loli.net/2021/12/01/VvleK2g8QSUCtHp.jpg)

2. 在“媒体库”->“图片”、“视频”中，切换列表和图标显示会出现问题
![IMG_1259.jpg](https://i.loli.net/2021/12/01/2bBdOifEMUsjCeG.jpg)
![IMG_1261.jpg](https://i.loli.net/2021/12/01/SBMagmtoIjx5qiW.jpg)

**Comment by alexiscn** [comment]
fixed in 1.1.17 build 20

请及时验收确认修复后关闭，谢谢。

**Comment by Kosette** [comment]
fixed in 1.1.17(20)
