### ISSUE TITLE
[Bug] 播放器图标错误

### ISSUE THREAD

**Issue by ChrisBDZ** [alexiscn/FileboxFeedback#93]
### 请确保您已阅读以上常见问题列表，并勾选下方的确认框。

- [X] 我已经仔细阅读上述常见问题列表 ["常见问题"](https://filebox.space/faq/)
- [x] 我已确认没有相同问题的ISSUE已被提出。

### 使用的Filebox版本

V1.1.31(118)

### 遇到的错误

播放器字幕图标不对（1是Apple播客）
![A9404ED7-0A88-48A3-B8ED-37A5870F2674](https://user-images.githubusercontent.com/67193145/160384520-cbd2fbcf-840a-4961-ad39-8a3d75e99b53.jpeg)
![C91ABAAA-B326-4993-8DC2-8FF72BB0432F](https://user-images.githubusercontent.com/67193145/160384528-64089010-dbc1-4e38-afc7-27a13662ac3d.jpeg)

**Comment by alexiscn** [comment]
fixed in 1.1.42
